import type { AppAction, AppState, DailyOperationsSummary } from '@gatsi/domain';
const API_ORIGIN = import.meta.env.VITE_API_URL ?? (import.meta.env.DEV ? 'http://localhost:4000' : '');
const API_URL = `${API_ORIGIN.replace(/\/$/, '')}/api`; const ACCESS='gatsi-access-token',REFRESH='gatsi-refresh-token';
type AuthResponse={accessToken?:string;refreshToken?:string;token?:string;state:AppState};
const save=(r:AuthResponse)=>{const access=r.accessToken??r.token;if(!access)throw new Error('The API returned an invalid authentication response.');localStorage.setItem(ACCESS,access);if(r.refreshToken)localStorage.setItem(REFRESH,r.refreshToken);else localStorage.removeItem(REFRESH);}; const clear=()=>{localStorage.removeItem(ACCESS);localStorage.removeItem(REFRESH);};
async function raw<T>(path:string,init?:RequestInit,retry=true):Promise<T>{const access=localStorage.getItem(ACCESS);let res:Response;try{res=await fetch(`${API_URL}${path}`,{...init,headers:{'content-type':'application/json',...(access?{authorization:`Bearer ${access}`} :{}),...init?.headers}});}catch{throw new Error(`Cannot reach the Gatsi API at ${API_URL}. Start or deploy the backend, then try again.`);}if(res.status===401&&retry&&path!=='/auth/refresh'){const refreshToken=localStorage.getItem(REFRESH);if(refreshToken){try{const renewed=await raw<AuthResponse>('/auth/refresh',{method:'POST',body:JSON.stringify({refreshToken})},false);save(renewed);return raw<T>(path,init,false);}catch{clear();}}}const body=await res.json();if(!res.ok)throw new Error(body.error||'Request failed.');return body;}
export async function apiLogin(username:string,password:string,localState?:AppState){const result=await raw<AuthResponse>('/auth/login',{method:'POST',body:JSON.stringify({username,password})},false);save(result);if(localState&&result.state.users.find(u=>u.id===result.state.activeUserId)?.role==='admin'&&!result.state.services.length){try{return await raw<AppState>('/bootstrap',{method:'POST',body:JSON.stringify(localState)});}catch{}}return result.state;}
export const apiLogout=async()=>{try{await raw('/auth/logout',{method:'POST'});}finally{clear();}};export const apiState=()=>raw<AppState>('/state');export const apiAction=(action:AppAction)=>raw<AppState>('/actions',{method:'POST',body:JSON.stringify(action)});export const hasApiSession=()=>Boolean(localStorage.getItem(ACCESS)||localStorage.getItem(REFRESH));
export const apiRequestPasswordReset=(identifier:string)=>raw<{ok:boolean;debugToken?:string}>('/auth/password-reset/request',{method:'POST',body:JSON.stringify({identifier})},false);
export const apiConfirmPasswordReset=(token:string,newPassword:string)=>raw<{ok:boolean}>('/auth/password-reset/confirm',{method:'POST',body:JSON.stringify({token,newPassword})},false);
export const apiChangePassword=(currentPassword:string,newPassword:string)=>raw<{ok:boolean}>('/account/password',{method:'POST',body:JSON.stringify({currentPassword,newPassword})});
export const apiConfirmVerification=(token:string)=>raw<{ok:boolean}>('/auth/verification/confirm',{method:'POST',body:JSON.stringify({token})},false);
export const apiVerifyCustomer=(userId:string)=>raw<AppState>('/admin/customers/verify',{method:'POST',body:JSON.stringify({userId})});
export const apiOperationsSummaries=()=>raw<{items:DailyOperationsSummary[]}>('/admin/operations-summaries');
export const apiGenerateOperationsSummary=()=>raw<{summary:DailyOperationsSummary}>('/admin/operations-summaries/generate',{method:'POST',body:'{}'});
