import AsyncStorage from '@react-native-async-storage/async-storage';import type{AppAction,AppState,DailyOperationsSummary}from'@gatsi/domain';import{Platform}from'react-native';declare const process:{env:{EXPO_PUBLIC_API_URL?:string}};
const host=Platform.OS==='android'?'10.0.2.2':'localhost',API_URL=`${process.env.EXPO_PUBLIC_API_URL||`http://${host}:4000`}/api`,ACCESS='gatsi-access-token',REFRESH='gatsi-refresh-token';type AuthResponse={accessToken?:string;refreshToken?:string;token?:string;state:AppState};
const save=async(r:AuthResponse)=>{const access=r.accessToken??r.token;if(!access)throw new Error('The API returned an invalid authentication response.');await AsyncStorage.setItem(ACCESS,access);if(r.refreshToken)await AsyncStorage.setItem(REFRESH,r.refreshToken);else await AsyncStorage.removeItem(REFRESH);};const clear=()=>AsyncStorage.multiRemove([ACCESS,REFRESH]);
async function raw<T>(path:string,init?:RequestInit,retry=true):Promise<T>{const access=await AsyncStorage.getItem(ACCESS);let res:Response;try{res=await fetch(`${API_URL}${path}`,{...init,headers:{'content-type':'application/json',...(access?{authorization:`Bearer ${access}`} :{}),...init?.headers}});}catch{throw new Error(`Cannot reach the Gatsi API at ${API_URL}. Check the backend address and try again.`);}if(res.status===401&&retry&&path!=='/auth/refresh'){const refreshToken=await AsyncStorage.getItem(REFRESH);if(refreshToken){try{const renewed=await raw<AuthResponse>('/auth/refresh',{method:'POST',body:JSON.stringify({refreshToken})},false);await save(renewed);return raw<T>(path,init,false);}catch{await clear();}}}const body=await res.json();if(!res.ok)throw new Error(body.error||'Request failed.');return body;}
export async function apiLogin(username:string,password:string,localState?:AppState){const result=await raw<AuthResponse>('/auth/login',{method:'POST',body:JSON.stringify({username,password})},false);await save(result);if(localState&&result.state.users.find(u=>u.id===result.state.activeUserId)?.role==='admin'&&!result.state.services.length){try{return await raw<AppState>('/bootstrap',{method:'POST',body:JSON.stringify(localState)});}catch{}}return result.state;}
export const apiLogout=async()=>{try{await raw('/auth/logout',{method:'POST'});}finally{await clear();}};export const apiState=()=>raw<AppState>('/state');export const apiAction=(action:AppAction)=>raw<AppState>('/actions',{method:'POST',body:JSON.stringify(action)});export const hasApiSession=async()=>Boolean(await AsyncStorage.getItem(ACCESS)||await AsyncStorage.getItem(REFRESH));
export const apiRequestPasswordReset=(identifier:string)=>raw<{ok:boolean;debugToken?:string}>('/auth/password-reset/request',{method:'POST',body:JSON.stringify({identifier})},false);
export const apiConfirmPasswordReset=(token:string,newPassword:string)=>raw<{ok:boolean}>('/auth/password-reset/confirm',{method:'POST',body:JSON.stringify({token,newPassword})},false);
export const apiConfirmVerification=(token:string)=>raw<{ok:boolean}>('/auth/verification/confirm',{method:'POST',body:JSON.stringify({token})},false);
export const apiVerifyCustomer=(userId:string)=>raw<AppState>('/admin/customers/verify',{method:'POST',body:JSON.stringify({userId})});
export type OperationsSummariesResponse={items:DailyOperationsSummary[]};
export type GenerateOperationsSummaryResponse={summary:DailyOperationsSummary};
export const apiOperationsSummaries=()=>raw<OperationsSummariesResponse>('/admin/operations-summaries');
export const apiGenerateOperationsSummary=(date?:string)=>raw<GenerateOperationsSummaryResponse>('/admin/operations-summaries/generate',{method:'POST',body:JSON.stringify(date?{date}:{})});
