import { Feather } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import React, { useState } from 'react';
import { KeyboardAvoidingView, Platform, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { PrimaryButton } from '../components/ui';
import { useAppStore } from '../store/AppStore';
import { apiLogin } from '../store/api';
import { colors, radius, shadow } from '../theme';

export function LoginScreen() {
  const { dispatch } = useAppStore();
  const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState('');
  const login = async () => { try { const remote = await apiLogin(username, password); setError(''); dispatch({ type: 'HYDRATE', state: remote }); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to sign in.'); } };
  return <SafeAreaView style={styles.safe}><KeyboardAvoidingView style={styles.safe} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><LinearGradient colors={[colors.primaryDark, colors.primary, '#16A865']} style={styles.hero}><View style={styles.logo}><Text style={styles.logoText}>G</Text></View><Text style={styles.brand}>Gatsi Comms</Text><Text style={styles.tagline}>Textile & Dry Cleaning Services</Text><View style={styles.heroBadge}><Feather name="shield" size={15} color="#fff" /><Text style={styles.heroBadgeText}>Secure, role-based account access</Text></View></LinearGradient><View style={styles.panel}><Text style={styles.title}>Welcome back</Text><Text style={styles.subtitle}>Enter the login details assigned to your verified account.</Text><View style={styles.form}><Text style={styles.label}>Username</Text><View style={styles.inputWrap}><Feather name="user" size={18} color={colors.primary} /><TextInput style={styles.input} value={username} onChangeText={(value) => { setUsername(value); setError(''); }} autoCapitalize="none" autoCorrect={false} autoComplete="username" placeholder="Enter username" placeholderTextColor={colors.subtle} /></View><Text style={styles.label}>Password</Text><View style={styles.inputWrap}><Feather name="lock" size={18} color={colors.primary} /><TextInput style={styles.input} value={password} onChangeText={(value) => { setPassword(value); setError(''); }} secureTextEntry={!showPassword} autoCapitalize="none" autoCorrect={false} autoComplete="current-password" placeholder="Enter password" placeholderTextColor={colors.subtle} onSubmitEditing={login} /><TouchableOpacity onPress={() => setShowPassword((current) => !current)}><Feather name={showPassword ? 'eye-off' : 'eye'} size={19} color={colors.muted} /></TouchableOpacity></View>{error ? <View style={styles.error}><Feather name="alert-circle" size={16} color={colors.red} /><Text style={styles.errorText}>{error}</Text></View> : null}<PrimaryButton title="Sign in" icon="arrow-right" disabled={!username.trim() || !password} onPress={login} /><Text style={styles.note}>Your role and branch permissions are verified when you sign in.</Text></View></View></KeyboardAvoidingView></SafeAreaView>;
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background }, hero: { paddingHorizontal: 26, paddingTop: 34, paddingBottom: 40, alignItems: 'center', borderBottomLeftRadius: 34, borderBottomRightRadius: 34 }, logo: { width: 68, height: 68, borderRadius: 22, backgroundColor: 'rgba(255,255,255,0.18)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.3)', alignItems: 'center', justifyContent: 'center' }, logoText: { color: '#fff', fontSize: 37, fontWeight: '900' }, brand: { color: '#fff', fontSize: 30, fontWeight: '900', marginTop: 14, letterSpacing: -0.8 }, tagline: { color: 'rgba(255,255,255,0.78)', fontSize: 14, marginTop: 5 }, heroBadge: { flexDirection: 'row', alignItems: 'center', gap: 7, paddingHorizontal: 13, paddingVertical: 8, borderRadius: 999, backgroundColor: 'rgba(0,0,0,0.12)', marginTop: 18 }, heroBadgeText: { color: '#fff', fontSize: 12, fontWeight: '700' }, panel: { flex: 1, paddingHorizontal: 22, paddingTop: 28 }, title: { color: colors.ink, fontSize: 25, fontWeight: '900' }, subtitle: { color: colors.muted, fontSize: 13, lineHeight: 19, marginTop: 7 }, form: { gap: 10, marginTop: 24 }, label: { color: colors.ink, fontSize: 13, fontWeight: '800', marginTop: 3 }, inputWrap: { minHeight: 54, flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 15, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, ...shadow }, input: { flex: 1, color: colors.ink, fontSize: 15 }, error: { flexDirection: 'row', alignItems: 'center', gap: 7, padding: 11, borderRadius: radius.sm, backgroundColor: colors.redSoft }, errorText: { flex: 1, color: colors.red, fontSize: 12, lineHeight: 17 }, note: { color: colors.subtle, textAlign: 'center', fontSize: 11, lineHeight: 16, marginTop: 2 },
});
