import { Feather } from '@expo/vector-icons';
import { branchRevenue, getActiveUser, money } from '@gatsi/domain';
import React from 'react';
import { Alert, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { AppHeader } from '../components/AppHeader';
import { Screen } from '../components/Screen';
import { Card, SectionTitle } from '../components/ui';
import { useAppStore } from '../store/AppStore';
import { colors, radius } from '../theme';

export function MoreScreen() {
  const { state, dispatch } = useAppStore();
  const user = getActiveUser(state)!;
  const logout = () => dispatch({ type: 'LOGOUT' });
  const reset = () => Alert.alert('Reset demo data?', 'This removes local changes and restores the sample orders.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Reset', style: 'destructive', onPress: () => dispatch({ type: 'RESET_DEMO' }) }]);
  return <Screen><AppHeader title="More" subtitle="Account, branches and workspace settings" /><Card style={styles.profile}><View style={[styles.avatar, { backgroundColor: user.avatarColor }]}><Text style={styles.avatarText}>{user.name.split(' ').map((part) => part[0]).join('').slice(0, 2)}</Text></View><View style={{ flex: 1 }}><Text style={styles.name}>{user.name}</Text><Text style={styles.role}>{user.role} · {user.jobTitle ?? user.email}</Text><Text style={styles.email}>{user.email}</Text></View><View style={styles.verified}><Feather name="check" size={14} color="#fff" /></View></Card>

  {user.role === 'admin' ? <><SectionTitle title="Branches" />{state.branches.map((branch) => { const orders = state.orders.filter((order) => order.branchId === branch.id); const staff = state.users.filter((member) => member.role === 'staff' && member.branchIds.includes(branch.id)); return <Card key={branch.id} style={styles.branchCard}><View style={styles.branchTop}><View style={styles.branchIcon}><Feather name="map-pin" size={20} color={colors.primary} /></View><View style={{ flex: 1 }}><Text style={styles.branchName}>{branch.name}</Text><Text style={styles.branchAddress}>{branch.address}</Text></View><View style={styles.openPill}><Text style={styles.openText}>Open</Text></View></View><View style={styles.branchStats}><View><Text style={styles.branchValue}>{orders.length}</Text><Text style={styles.branchLabel}>Orders</Text></View><View><Text style={styles.branchValue}>{staff.length}</Text><Text style={styles.branchLabel}>Staff</Text></View><View><Text style={styles.branchValue}>{money(branchRevenue(state, branch.id))}</Text><Text style={styles.branchLabel}>Revenue</Text></View></View></Card>; })}</> : null}

  {user.role !== 'customer' ? <><SectionTitle title={user.role === 'admin' ? 'Team today' : 'Branch teammates'} />{state.users.filter((member) => member.role === 'staff' && (user.role === 'admin' ? state.activeBranchId === 'all' || member.branchIds.includes(state.activeBranchId) : member.branchIds.some((id) => user.branchIds.includes(id)))).map((member) => <Card key={member.id} style={styles.person}><View style={[styles.personAvatar, { backgroundColor: member.avatarColor }]}><Text style={styles.personAvatarText}>{member.name.split(' ').map((part) => part[0]).join('').slice(0, 2)}</Text></View><View style={{ flex: 1 }}><Text style={styles.personName}>{member.name}</Text><Text style={styles.personRole}>{member.jobTitle}</Text></View><View style={[styles.presence, member.clockedIn && styles.presenceIn]}><Text style={[styles.presenceText, member.clockedIn && styles.presenceTextIn]}>{member.clockedIn ? 'On shift' : 'Off shift'}</Text></View></Card>)}</> : <><SectionTitle title="Help & contact" /><Card style={styles.helpCard}><MenuItem icon="phone" title="Call Gatsi Comms" detail={state.branches.find((branch) => branch.id === state.activeBranchId)?.phone ?? state.branches[0].phone} /><MenuItem icon="message-circle" title="WhatsApp support" detail="Chat with a garment care adviser" /><MenuItem icon="award" title="Loyalty programme" detail="Earn one point for every dollar spent" /></Card></>}

  <SectionTitle title="Workspace" />
  <Card style={styles.menu}><MenuItem icon="user" title="Switch demo role" detail="Admin, staff or customer" onPress={logout} /><MenuItem icon="refresh-cw" title="Reset demo data" detail="Restore the original sample records" onPress={reset} danger /></Card>
  <Text style={styles.version}>Gatsi Comms Suite · Version 1.0.0</Text></Screen>;
}

function MenuItem({ icon, title, detail, onPress, danger }: { icon: keyof typeof Feather.glyphMap; title: string; detail: string; onPress?: () => void; danger?: boolean }) {
  return <TouchableOpacity disabled={!onPress} onPress={onPress} style={styles.menuItem}><View style={[styles.menuIcon, danger && { backgroundColor: colors.redSoft }]}><Feather name={icon} size={18} color={danger ? colors.red : colors.primary} /></View><View style={{ flex: 1 }}><Text style={[styles.menuTitle, danger && { color: colors.red }]}>{title}</Text><Text style={styles.menuDetail}>{detail}</Text></View>{onPress ? <Feather name="chevron-right" size={19} color={colors.subtle} /> : null}</TouchableOpacity>;
}

const styles = StyleSheet.create({
  profile: { padding: 16, flexDirection: 'row', alignItems: 'center', gap: 12 }, avatar: { width: 58, height: 58, borderRadius: 19, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: '#fff', fontSize: 18, fontWeight: '900' }, name: { color: colors.ink, fontSize: 17, fontWeight: '900' }, role: { color: colors.primary, fontSize: 11, fontWeight: '700', textTransform: 'capitalize', marginTop: 4 }, email: { color: colors.muted, fontSize: 10, marginTop: 3 }, verified: { width: 25, height: 25, borderRadius: 13, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' },
  branchCard: { padding: 15, marginBottom: 11 }, branchTop: { flexDirection: 'row', alignItems: 'center', gap: 11 }, branchIcon: { width: 43, height: 43, borderRadius: 14, backgroundColor: colors.primaryLight, alignItems: 'center', justifyContent: 'center' }, branchName: { color: colors.ink, fontSize: 14, fontWeight: '800' }, branchAddress: { color: colors.muted, fontSize: 10, marginTop: 4 }, openPill: { backgroundColor: colors.primaryLight, borderRadius: 99, paddingHorizontal: 9, paddingVertical: 5 }, openText: { color: colors.primary, fontSize: 9, fontWeight: '900' }, branchStats: { flexDirection: 'row', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: colors.border, paddingTop: 13, marginTop: 13 }, branchValue: { color: colors.ink, fontSize: 14, fontWeight: '900' }, branchLabel: { color: colors.subtle, textTransform: 'uppercase', fontSize: 8, marginTop: 3 },
  person: { flexDirection: 'row', alignItems: 'center', padding: 13, gap: 11, marginBottom: 9 }, personAvatar: { width: 43, height: 43, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, personAvatarText: { color: '#fff', fontSize: 11, fontWeight: '900' }, personName: { color: colors.ink, fontSize: 13, fontWeight: '800' }, personRole: { color: colors.muted, fontSize: 10, marginTop: 3 }, presence: { backgroundColor: colors.background, paddingHorizontal: 9, paddingVertical: 5, borderRadius: 99 }, presenceIn: { backgroundColor: colors.primaryLight }, presenceText: { color: colors.muted, fontSize: 9, fontWeight: '800' }, presenceTextIn: { color: colors.primary },
  helpCard: { paddingHorizontal: 14 }, menu: { paddingHorizontal: 14 }, menuItem: { flexDirection: 'row', alignItems: 'center', gap: 11, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: colors.border }, menuIcon: { width: 39, height: 39, borderRadius: 12, backgroundColor: colors.primaryLight, alignItems: 'center', justifyContent: 'center' }, menuTitle: { color: colors.ink, fontSize: 13, fontWeight: '800' }, menuDetail: { color: colors.muted, fontSize: 10, marginTop: 3 }, version: { color: colors.subtle, fontSize: 10, textAlign: 'center', marginTop: 24 },
});
