import { CheckCircle2, Eye, EyeOff, LockKeyhole, PackageCheck, Shirt, Sparkles } from 'lucide-react';
import { useState } from 'react';
import { Button } from '../components/ui';
import { useAppStore } from '../store/AppStore';
import { apiLogin } from '../store/api';

export function LoginPage() {
  const { dispatch } = useAppStore();
  const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false);
  const login = async (event: React.FormEvent) => { event.preventDefault(); setSubmitting(true); try { const remote = await apiLogin(username, password); setError(''); dispatch({ type: 'HYDRATE', state: remote }); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to sign in.'); setSubmitting(false); } };
  return <div className="login-page"><section className="login-story"><div className="login-brand"><span>G</span><div><strong>Gatsi Comms</strong><small>Textile & Dry Cleaning Services</small></div></div><div className="login-copy"><span className="story-pill"><Sparkles /> Operations, beautifully organised</span><h1>Every garment.<br /><em>Every stage.</em><br />Always visible.</h1><p>A secure workspace for counter intake, cleaning workflows, branch teams, inventory, payments, pickups and customers.</p><div className="story-points"><span><PackageCheck /> Traceable order care</span><span><Shirt /> Service-based pricing</span><span><CheckCircle2 /> Verified account access</span></div></div><div className="login-orbit"><i /><i /><i /><Shirt /></div></section><section className="login-panel"><div className="login-form"><span className="eyebrow">Secure account access</span><h2>Welcome back</h2><p>Enter the login details assigned to your account.</p><form className="customer-login" onSubmit={login}><label>Username<div className="auth-input"><input required value={username} onChange={(event) => { setUsername(event.target.value); setError(''); }} autoComplete="username" autoFocus /><LockKeyhole /></div></label><label>Password<div className="auth-input"><input required type={showPassword ? 'text' : 'password'} value={password} onChange={(event) => { setPassword(event.target.value); setError(''); }} autoComplete="current-password" /><button type="button" onClick={() => setShowPassword((current) => !current)} aria-label={showPassword ? 'Hide password' : 'Show password'}>{showPassword ? <EyeOff /> : <Eye />}</button></div></label>{error ? <span className="login-error" role="alert">{error}</span> : null}<Button className="login-button" type="submit" disabled={submitting || !username.trim() || !password}>Sign in <span>→</span></Button></form><small className="auth-note">Accounts are verified and access is limited by assigned role and branch.</small></div></section></div>;
}
